config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :customers, path: 'customers', controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    omniauth_callbacks: 'public/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    get '/privacy_policy', to: 'homes#privacy_policy'
    resources :customers, only:[:show]
    get '/current_customer/profile', to: 'customers#profile'
    patch '/current_customer', to: 'customers#update'
    get '/current_customer/cancel', to: 'customers#cancel'
    patch '/current_customer/quit', to: 'customers#quit'
    resources :lessons do
      collection do
        get :search
        post :result
      end
    end
    resources :cart_lessons, only:[:create, :index, :destroy]
    resources :orders, only:[:new] do
      collection do
        post :confirmation
        get :completed
        post :create, path: 'completed'
      end
    end
    resources :addresses, except:[:new, :show]
    resources :have_lessons, only:[:index, :show, :update]
    resources :evaluations, only:[:new, :create, :show, :index]
    resources :comments
    resources :payment_methods, except:[:new, :show, :edit, :update]
    get "/callback", to:"calendars#initialize"
    get "/calendar/index", to:"calendars#index"
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, except:[:new, :create, :destroy]
    resources :categories, except:[:new, :show, :edit]
    resources :lessons, except:[:new, :create, :edit, :update]
    resources :tags, only:[:index, :destroy]
    resources :evaluations, only:[:show, :index]
    resources :orders, only:[:show, :update]
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :category
  belongs_to :customer

  has_many :tag_lists, dependent: :destroy
  has_many :tags, through: :tag_lists
  has_many :evaluations, dependent: :destroy
  has_many :cart_lessons, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :have_lessons, dependent: :destroy

  enum attending_style: { online: 0, offline: 1 }

  with_options presence: true do
    validates :name
    validates :content
    validates :attending_style
    validates :contract_period
    validates :price
    validates :access
  end

  validates :attending_style, inclusion: { in: ["online", "offline"] }
  validates :is_in_lecture, inclusion: { in: [true, false] }

  with_options numericality: true do
    validates :contract_period
    validates :price
  end

  validate :payment_methods_presence, on: :create

  def payment_methods_presence
    if customer.payment_methods.blank?
      errors.add(:method, "が必要です")
    end
  end

  def tax_price
    self.price * 1.1
  end


  def save_tag(made_tags)
    current_tags=self.tags.pluck(:name) unless self.tags.nil?
    old_tags=current_tags - made_tags
    new_tags=made_tags - current_tags

    old_tags.each do |old|
      old_tag=Tag.find_by(name: old)
      old_tag_list=TagList.find_by(tag_id: old_tag.id, lesson_id: self.id)
      
      if TagList.where(tag_id: old_tag.id).length > 1
        old_tag_list.delete
      else
        old_tag.delete
        old_tag_list.delete
      end
    end

    new_tags.each do |new|
      new_tag=Tag.find_or_create_by(name: new)
      self.tags << new_tag
    end
  end

  scope :search, -> (search_params) do
    return if search_params.blank?

    category_id(search_params[:category_id])
      .attending_style(search_params[:attending_style])
      .access(search_params[:access])
      .price(search_params[:price])
  end

  scope :category_id, -> (category_id) { where('category_id = ? ', category_id) if category_id.present? }
  scope :attending_style, -> (attending_style) { where('attending_style = ?', attending_style) if attending_style.present? }
  scope :access, -> (access) { where('access LIKE ?', "%#{access}%") if access.present? }
  scope :price, -> (price) { where('price <= ?', price) if price.present? }

end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @lessons=Lesson.all
  end

  def show
    @lesson=Lesson.find(params[:id])
    @evaluations=Evaluation.where(lesson_id: @lesson.id)
  end

  def destroy
    @lesson=Lesson.find(params[:id])
    @lesson.destroy
    redirect_to admin_lessons_path
  end

end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
end

app/views/admin/lessons/index.html.erb
<%= render 'admin/after_sign_in_nav' %>
<div class="container">
  <div class="row">
    <%= render partial: 'layouts/sidebar', locals: { categories: @categories, tags: @tags } %>
    <div class="col-9 offset-md-1">
      <h2 class="mt-5">講座一覧</h2>
      <table class="table table-hover table-sm">
        <thead>
          <tr>
            <th>講座名</th>
            <th>アクセス</th>
            <th>契約期間</th>
            <th>税抜価格</th>
            <th>開講状況</th>
            <th>最終更新日</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @lessons.each do |lesson| %>
          <tr>
            <td>
              <%= link_to admin_lesson_path(lesson.id), class: "link-dark" do %>
                <%= lesson.name %>
              <% end %>
            </td>
            <td><%= lesson.attending_style_i18n %>　<%= lesson.access %></td>
            <td><%= contract_period(lesson.contract_period) %></td>
            <td><%= lesson.price %>円</td>
            <td><%= is_in_lecture(lesson.is_in_lecture) %></td>
            <td><%= l lesson.updated_at %></td>
            <td><%= link_to "削除", "/admin/lessons/#{lesson.id}", method: :delete, class: "btn btn-danger btn-sm" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/lessons/show.html.erb
<%= render 'admin/after_sign_in_nav' %>
<div class="container">
  <div class="row">
    <%= render partial: 'layouts/sidebar', locals: { categories: @categories, tags: @tags } %>
    <div class="col-9 offset-md-1">
      <h2 class="mt-5">講座詳細画面</h2>
      <h2 class="col mt-5">【<%= @lesson.name %>】</h2>
      <div class="row mt-5">
        <h5 class="col-2">会員名</h5>
        <p class="col-3 fs-5 border">
        <%= link_to admin_customer_path(@lesson.customer_id), class: "link-dark" do %>
          <%= @lesson.customer.nickname %>
        <% end %>
        </p>
      </div>
      <div class="row mt-5">
        <h5 class="col-2">評価平均</h4>
        <% if @evaluations.present? %>
          <div class="col-2">
            <%= form_with url: evaluations_path, method: :get, local:true do |f| %>
              <%= f.hidden_field:lesson_id, :value => @lesson.id %>
              <%= f.submit "#{evaluation_average(@evaluations)}", class: "fs-5" %>
            <% end %>
          </div>
        <% else %>
          <p class="col-2 fs-5 border">評価なし</p>
        <% end %>
      </div>
      <div class="row mt-5">
        <h5 class="col-2">受講者数</h5>
        <p class="col-2 fs-5 border"><%= HaveLesson.where(lesson_id: @lesson.id).count %>人</p>
      </div>
      <div class="col-6 mt-5">
        <h5>内容</h5>
        <p class="fs-5 border ms-3"><%= @lesson.content %></p>
      </div>
      <div class="row mt-5">
        <div class="col-3">
          <h5>受講形態</h5>
          <p class="fs-5 border ms-3"><%= @lesson.attending_style_i18n %></p>
        </div>
        <div class="col-6 offset-md-1">
          <h5>アクセス先</h5>
          <p class="fs-5 border ms-3"><%= @lesson.access %></p>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col-3">
          <h5>カテゴリー</h5>
          <p class="fs-5 border ms-3"><%= @lesson.category.name %></p>
        </div>
        <div class="col-6 offset-md-1">
          <h5>タグ</h5>
          <p class="fs-5 ms-3">
            <% @lesson.tags.each do |tag| %>
              <button class="btn btn-success"><%= tag.name %></button>
            <% end %>
          </p>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col-3">
          <h5>契約期間</h5>
          <p class="fs-5 border"><%= contract_period(@lesson.contract_period) %></p>
        </div>
        <div class="col-3 offset-md-2">
          <h5>税抜価格</h5>
          <div class="row ms-3">
            <p class="fs-5 border col-5"><%= @lesson.price %></p>
            <p class="fs-5 col-1">円</p>
          </div>
        </div>
      </div>
      <div class="row mt-5 offset-md-3">
        <%= link_to "一覧へ戻る", admin_lessons_path, class: "btn btn-primary col-2" %>
      </div>
    </div>
  </div>
</div>