config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :customers, path: 'customers', controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    omniauth_callbacks: 'public/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    get '/privacy_policy', to: 'homes#privacy_policy'
    resources :customers, only:[:show]
    get '/current_customer/profile', to: 'customers#profile'
    patch '/current_customer', to: 'customers#update'
    get '/current_customer/cancel', to: 'customers#cancel'
    patch '/current_customer/quit', to: 'customers#quit'
    resources :lessons do
      collection do
        get :search
        post :result
      end
    end
    resources :cart_lessons, only:[:create, :index, :destroy]
    resources :orders, only:[:new] do
      collection do
        post :confirmation
        get :completed
        post :create, path: 'completed'
      end
    end
    resources :addresses, except:[:new, :show]
    resources :have_lessons, only:[:index, :show, :update]
    resources :evaluations, only:[:new, :create, :show, :index]
    resources :comments
    resources :payment_methods, except:[:new, :show, :edit, :update]
    get "/callback", to:"calendars#initialize"
    get "/calendar/index", to:"calendars#index"
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, except:[:new, :create, :destroy]
    resources :categories, except:[:new, :show, :edit]
    resources :lessons, except:[:new, :create, :edit, :update]
    resources :tags, only:[:index, :destroy]
    resources :evaluations, only:[:show, :index]
    resources :orders, only:[:show, :update]
  end
end

app/views/layouts/_after_sign_in_nav.html.erb
<div class="row d-flex bg-info">
  <div class="me-auto col-3">
    <%= link_to root_path do %>
      <%= image_tag '卒業生アイコン.png', height: 100, width: 100 %>
    <% end %>
  </div>
  <nav class="col-3 navbar navbar-expand-lg navbar-light">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "HOME", root_path, class: "nav-link h5 me-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", customer_path(customer.id), class: "nav-link h5 me-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link h5" %>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_before_paid_nav.html.erb
<nav class="navbar navbar-light bg-info px-3">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag '卒業生アイコン.png', height: 70, width: 70 %>LERN COMMUNITY
    <% end %>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <%= link_to "HOME", root_path, class: "nav-link link-dark" %>
        </li>
        <li class="nav-item">
          <%= link_to "会員登録", new_customer_registration_path, class: "nav-link link-dark" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link link-dark" %>
        </li>
      </ul>
  </div>
</nav>
<%= render 'layouts/flash' %>

app/views/layouts/_before_sign_in_nav.html.erb
<nav class="navbar navbar-light bg-info px-3">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag '卒業生アイコン.png', height: 70, width: 70 %>LERN COMMUNITY
    <% end %>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <%= link_to "HOME", root_path, class: "nav-link link-dark" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規会員登録", new_customer_registration_path, class: "nav-link link-dark" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path, class: "nav-link link-dark" %>
        </li>
      </ul>
  </div>
</nav>
<%= render 'layouts/notifications' %>

app/views/layouts/_errors.html.erb
<ul class="alert">
  <% item.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer bg-info d-flex justify-content-center mt-5 row">
  <p class="lh-lg text-center">Copyright © 2022 LearnCommunity All Rights Reserved.</p>
  <div class="d-flex justify-content-end"><%= link_to "プライバシーポリシー", privacy_policy_path, class: "me-5 mb-3 text-dark" %></div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="col-2 mt-5 border-end">
    <ul class="list-unstyled ps-0">
      <li class="mb-1 mt-5">
        <button class="btn btn-toggle align-items-center rounded collapsed fs-5 fw-bold" data-bs-toggle="collapse" data-bs-target="#category-collapse" aria-expanded="true">
          カテゴリー
        </button>
        <div class="collapse ms-1" id="category-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <% categories.each do |category| %>
            <li class="m-3"><%= category.name %>(<%= category.lessons.where(is_in_lecture: true).count %>)</li>
          <% end %>
          </ul>
        </div>
      </li>
      <li class="border-top my-3"></li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed fs-5 fw-bold" data-bs-toggle="collapse" data-bs-target="#tag-collapse" aria-expanded="false">
          タグ
        </button>
        <div class="collapse ms-1" id="tag-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <% tags.each do |tag| %>
            <li class="m-3"><%= tag.name %>(<%= tag.tag_lists.count %>)</li>
          <% end %>
          </ul>
        </div>
      </li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnCommunity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>